title: "Cesbo"
author: "Cesbo Team"
copyright: "© 2021, Cesbo OU; all rights reserved."
contentDir: "content/en"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
disableKinds:
- "RSS"
- "sitemap"

params:
  twitter: "@cesbo"

languages:
  en:
    languageName: "English"
    description: "Professional software for Digital TV Broadcasting"
    weight: 1

    menu:
      main:
      - name: "Pricing"
        weight: 2
        url: "/pricing/"
      - name: "Profile"
        weight: 3
        url: "/profile/"
      footer:
      - name: "Contact Us"
        weight: 1
        url: "/help/"

  ru:
    languageName: "Русский"
    description: "Профессиональное программное обеспечение для трансляции Цифрового ТВ"
    weight: 2
    contentDir: "content/ru"

    menu:
      main:
      - name: "Цены"
        weight: 2
        url: "/pricing/"
      - name: "Профиль"
        weight: 3
        url: "/profile/"
      footer:
      - name: "Написать нам"
        weight: 1
        url: "/help/"
