title: Cesbo
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
disableKinds:
- RSS
- sitemap

params:
  cdn: https://cdn.cesbo.dev
  repository: https://github.com/cesbo/docs
  twitter: "@cesbo"

minify:
  minifyOutput: false

outputs:
  home:
  - html
  - json

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true

languages:
  en:
    languageName: "English"
    description: "Professional software for Digital TV Broadcasting"
    weight: 1

  ru:
    languageName: "Русский"
    description: "Профессиональное программное обеспечение для трансляции Цифрового ТВ"
    weight: 2
