name: deploy-action
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Copy project to temporary directory
        run: |
          ssh root@${{ secrets.SSH_HOST }} "
            cd /opt/help &&
            rm -rf tmp &&
            mkdir -p tmp
          "
          tar -zcf - -C .output . | ssh root@${{ secrets.SSH_HOST }} "tar -C /opt/help/tmp -zxf -"

      - name: Deploy project
        run: |
          ssh root@${{ secrets.SSH_HOST }} "
            cd /opt/help &&
            pm2 stop pm2.config.json &&
            rm -rf dist &&
            mv tmp dist &&
            pm2 start -a pm2.config.json
          "

      - name: Cleanup
        run: rm -rf ~/.ssh
